[theme]
primaryColor              = "#63b3ed"
backgroundColor           = "#383f4a"
secondaryBackgroundColor  = "#424e5c"
textColor                 = "#dceeff"
font                      = "sans serif"
